### __KNN__ (copilot response)

__k-Nearest Neighbors__ (k-NN) is a non-parametric, lazy learning algorithm used for classification and regression. It operates by finding the k nearest neighbors to a query instance and making predictions based on the majority class (for classification) or average (for regression) of these neighbors.

#### Steps in k-NN Algorithm:

1. __Choose the number of neighbors (k):__ This is a `hyperparameter` that you set before running the algorithm.

2. __Calculate the distance:__ Compute the distance between the query instance and `all` the training instances. Common distance metrics include Euclidean distance, Manhattan distance, etc.

3. __Find the k nearest neighbors:__ Identify the k training instances that are closest to the query instance.

4. __Make a prediction:__ For classification, the `majority` class among the `k neighbors` is the predicted class. For **regression**, the `average` value of the `k neighbors` is the predicted value.

In [37]:
import numpy as np
from sklearn.datasets import load_iris 
from sklearn.model_selection import train_test_split 
from sklearn.datasets import make_regression

In [38]:
iris = load_iris() 
X, y = iris.data, iris.target 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) 
print(X_train.shape, X_test.shape)

(120, 4) (30, 4)


In [39]:
from KNN.Metrics import Metrics
from KNN.KNN import KNN



knn = KNN(k=3, distance_metric=Metrics.Lp, p=1) 
# print(X_train.shape, X_test.shape)
knn.fit(X_train, y_train) 
predictions = knn.predict(X_test) 
accuracy = np.mean(predictions == y_test)
print(predictions, y_test,sep="\n")
print(accuracy)



[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
1.0


#### __Variants of k-NN Algorithm__

1. __Weighted k-NN:__ 
        In the standard k-NN algorithm, each of the k nearest neighbors contributes equally to the prediction. In the weighted k-NN, each neighbor is weighted by its distance, with `closer neighbors having more influence` than distant ones.
        $$ \text{Weight}(d_i) = \frac{1}{d_i + \epsilon} $$
        where $d_i$ is the distance of the i-th neighbor and $\epsilon$ is a small value to avoid division by zero.


In [40]:
knn = KNN(k=117, distance_metric=Metrics.Lp, weighted=True, p=1) 
# print(X_train.shape, X_test.shape)
knn.fit(X_train, y_train) 
predictions = knn.predict(X_test) 
accuracy = np.mean(predictions == y_test)
print(predictions, y_test,sep="\n")
print(accuracy)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
1.0


2. __Distance-Weighted k-NN:__
   
    + In this variant, the contribution of each neighbor is weighted by the inverse of its distance, allowing closer neighbors to have a larger impact on the prediction.

    $$\hat{y} = \frac{\sum_{i=1}^k \frac{y_i}{d_i}}{\sum_{i=1}^k \frac{1}{d_i}}$$

    where $y_i$ is the value of the i-th neighbor and $d_i$ is its distance.

In [41]:
from KNN.Metrics import Metrics
from KNN.DWkNN import DWkNN


print(X_train.shape, X_test.shape, y_train.shape) 
knn = DWkNN(k=117, distance_metric=Metrics.Lp, p=2) 
# print(X_train.shape, X_test.shape)
knn.fit(X_train, y_train) 
predictions = knn.predict(X_test)

# print(f"{array_preds:.2f}")
predictions = np.array([round(pred) for pred in predictions]) 
accuracy = np.mean(predictions == y_test)
# print(accuracy)
print(f"Accuracy: {accuracy:.2f}")
print( y_test, predictions, sep="\n")

(120, 4) (30, 4) (120,)
Accuracy: 0.77
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
[1 0 1 1 1 0 1 1 1 1 1 0 0 0 0 1 2 1 1 2 0 1 0 2 1 1 1 2 0 0]


3. __k-NN for Regression:__
    
    + In k-NN regression, the prediction is the average of the k nearest neighbors' values.

    $$\hat{y} = \frac{1}{k} \sum_{i=1}^k y_i$$


In [42]:


X, y = make_regression(n_samples=700, n_features=1, noise=3)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) 
print(X_train.shape, X_test.shape, y_train.shape)


(560, 1) (140, 1) (560,)


In [43]:
from KNN.Metrics import Metrics
from KNN.KNNRegressor import KNNRegressor

knnReg = KNNRegressor(k=5, distance_metric=Metrics.Lp, p=2)
knnReg.fit(X_train, y_train)
predictions = knnReg.predict(X_test)

mse = np.mean((predictions-y_test)**2)
print(f"MSE: {mse:.2f}")

MSE: 69.61


3. __KNN For Regression__

    + Weighted k-NN Regression:

        $$w_i = \frac{1}{d(x_q, x_i) + \epsilon}$$

    + Weighted Prediction:
        $$ \hat{y}_q = \frac{\sum_{i=1}^k w_i y_i}{\sum_{i=1}^{k} w_i} $$

In [44]:
from KNN.Metrics import Metrics
from KNN.KNNRegressor import KNNRegressor

knnReg = KNNRegressor(k=3, distance_metric=Metrics.Lp,weighted=True, p=2)
knnReg.fit(X_train, y_train)
predictions = knnReg.predict(X_test)

mse = np.mean((predictions-y_test)**2)
print(f"MSE: {mse:.2f}")

MSE: 37.15


# Curse of Dimensionality in k-NN

The __Curse of Dimensionality__ refers to various phenomena that arise when analyzing and organizing data in high-dimensional spaces. In the context of the k-Nearest Neighbors (k-NN) algorithm, it significantly impacts the performance and accuracy of the algorithm. As the __number of dimensions increases__, the __volume of the space increases exponentially__, making data points __sparse__ and the __distance between points less meaningful__.

+ `Mathematical Explanation`
    
    1. __Distance Concentration:__ In high dimensions, the distance between any two points tends to become similar, making it difficult to distinguish between near and far points. This phenomenon can be demonstrated mathematically.
        + For a point $x$ in a high-dimensional space, consider $d_i$ as the distance to the i-th nearest neighbor.
        + As the number of dimensions $d$ increases, the ratio of the distance to the farthest point $d_{\text{max}}$ to the nearest point $d_{\text{min}}$ approaches 1:
        $$ \lim_{d \to \infty} \frac{d_{\text{max}}}{d_{\text{min}}} \to 1$$